### ISSUE TITLE
Error when installing dependency Minify-html on a ARM64 device

### ISSUE THREAD

**Issue by GoOz** [AleksandrHovhannisyan/eleventy-plugin-code-demo#4]
Not really a bug from your plugin but really a bug on one of your dependency `@minify-html`.
Here is [the issue](https://github.com/wilsonzlin/minify-html/issues/119) and there's a working workaround in the comments.

I thought you should know about it. Maybe you'll feel like adding a disclaimer or switching library or whatever.

**Comment by AleksandrHovhannisyan** [comment]
Oof, that sucks. I'll see if I can test this on an ARM mac later.

I'll also look into alternatives, but as far as I can recall from my testing, this was the fastest package.

**Comment by AleksandrHovhannisyan** [comment]
So unfortunately, I only have an Intel Mac (work laptop) and a Windows laptop (personal) that I can test with. I can accept PRs to replace the library with an equivalent one, so long as it doesn't slow down builds considerably (`@minify-html` is quite lightweight). @GoOz Were you able to get the workaround to work for you? If so, I can link to it in the docs.

**Comment by GoOz** [comment]
Yes [this workaround](https://github.com/wilsonzlin/minify-html/issues/119#issuecomment-1688113448) worked for me, so I'd say it's not really a blocker for now.

**Comment by AleksandrHovhannisyan** [comment]
@GoOz Thanks, I've updated the installation docs to link to the workaround. Closing this issue for now, but feel free to reopen it if the workaround stops working for some reason.

**Comment by AleksandrHovhannisyan** [comment]
Hey, quick update: I ran into this issue myself out of the blue. I migrated the project to use a different, backwards-compatible minifier that doesn't run into this problem. The only caveat is that the shortcode is now async and requires Eleventy v3.0+ with Node >= 18 and ESM.
